export const NEW_PLAYER_MODAL = 'NEW_PLAYER';
export const DELETE_PLAYER_MODAL = 'DELETE_PLAYER_MODAL';
export const PLAYER_DETAILS_MODAL = 'PLAYER_DETAILS_MODAL';
export const ACCOUNT_REFILL_SUCCESS = 'ACCOUNT_REFILL_SUCCESS';
export const SET_WITHDRAW_MODAL = 'SET_WITHDRAW_MODAL';
