export const NEW_PLAYER_MODAL = 'NEW_PLAYER';
export const DELETE_PLAYER_MODAL = 'DELETE_PLAYER_MODAL';
export const PLAYER_DETAILS_MODAL = 'PLAYER_DETAILS_MODAL';
export const ACCOUNT_REFILL_SUCCESS = 'ACCOUNT_REFILL_SUCCESS';
export const AMOUNT_DIALOG_MODAL = 'AMOUNT_DIALOG_MODAL';

export const WITHDRAW_FROM_ACCOUNT = 'WITHDRAW_FROM_ACCOUNT';
export const ADD_BANK_DEBT = 'ADD_BANK_DEBT';
